services:
  servers:
    # platform: linux/amd64
    container_name: acs-core-service-prod
    image: ghcr.io/asc-base/acs-core-service:staging-877835f7b55a940a1e6fba5703210bbaa1de8406
    restart: unless-stopped
    environment:
      APP_PORT: ${APP_PORT:?APP_PORT must be set}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      DATABASE_URL: ${DATABASE_URL}
      HTTPONLY: ${HTTPONLY}
      SECURE: ${SECURE}
      ENVIRONMENT: prod
      APP_HOST: ${APP_HOST}
      SECRET_JWT: ${SECRET_JWT}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET must be set}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:?BETTER_AUTH_URL must be set}
      JWT_EXPIRATION_HOURS: ${JWT_EXPIRATION_HOURS}
      ALLOW_ORIGIN: ${ALLOW_ORIGIN}
      SKIP_MIGRATE: ${SKIP_MIGRATE}
      RUN_SEED: ${RUN_SEED}
    networks:
      - acs-prod-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=acs-prod-network
      - "traefik.http.routers.acs-core.rule=Host(`acs.kmutt.ac.th`) && (Path(`/api`) || PathPrefix(`/api/`))"
      - traefik.http.routers.acs-core.entrypoints=web
      - traefik.http.routers.acs-core.priority=100
      - traefik.http.routers.acs-core.service=acs-core
      - traefik.http.services.acs-core.loadbalancer.server.port=${APP_PORT:?APP_PORT must be set}

networks:
  acs-prod-network:
    external: true
    name: acs-prod-network
