services:
  database:
    container_name: acs-website-database-dev
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./databasepg:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - acs-dev-network

  servers:
    container_name: acs-website-server-dev
    image: ghcr.io/narutchai01/acs-core-service:1.0.55
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TIMEZONE: ${TIMEZONE}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      HTTPONLY: ${HTTPONLY}
      SECURE: ${SECURE}
      ENVIRONMENT: development
      APP_HOST: ${APP_HOST}
      SECRET_JWT: ${SECRET_JWT}
      JWT_EXPIRATION_HOURS: ${JWT_EXPIRATION_HOURS}
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${APP_PORT}/api/v1/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - acs-dev-network
      - gateway-nginx

  # portal:
  #   container_name: acs-website-portal-dev
  #   image: ghcr.io/narutchai01/acs-fe:v3.1.3
  #   restart: unless-stopped
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   environment:
  #     API_URL: ${API_URL}
  #     NODE_ENV: development
  #     PORT: ${APP_PORT}
  #   # depends_on:
  #   #   servers:
  #   #     condition: service_healthy
  #   networks:
  #     - gateway-nginx

networks:
  acs-dev-network:
    driver: bridge
  gateway-nginx:
    external: true
