services:
  portal:
    container_name: acs-website-portal-staging
    image: ghcr.io/asc-base/acs-portal:staging-f5b7afe6289eb9fb537d421b33547f98cb64e97a
    restart: unless-stopped
    environment:
      API_URL: ${API_URL}
      NODE_ENV: staging
      # PORT: ${PORTAL_PORT}
    # depends_on:
    #   servers:
    #     condition: service_healthy
